DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS trimesters CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS warnings CASCADE;
DROP TABLE IF EXISTS registrations CASCADE;
DROP TABLE IF EXISTS final_exams CASCADE;
DROP TABLE IF EXISTS final_grades CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL
);
ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT ck_users_type CHECK (type IN ('STUDENT', 'TEACHER', 'ADMIN'));

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    year INT NOT NULL
);
ALTER TABLE classes ADD CONSTRAINT pk_classes PRIMARY KEY (id);

CREATE TABLE trimesters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    max_points DECIMAL(5,2) NOT NULL,
    min_points DECIMAL(5,2) NOT NULL
);
ALTER TABLE trimesters ADD CONSTRAINT pk_trimesters PRIMARY KEY (id);

CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(200) NOT NULL
);
ALTER TABLE subjects ADD CONSTRAINT pk_subjects PRIMARY KEY (id);

CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    trimester_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    max_score DECIMAL(5, 2) NOT NULL,
    exam_date DATE NOT NULL
);
ALTER TABLE exams ADD CONSTRAINT pk_exams PRIMARY KEY (id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_classes FOREIGN KEY (class_id) REFERENCES classes(id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_users FOREIGN KEY (teacher_id) REFERENCES users(id);

CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    grade DECIMAL(5,2) NOT NULL
);
ALTER TABLE grades ADD CONSTRAINT pk_grades PRIMARY KEY (id);
ALTER TABLE grades ADD CONSTRAINT uk_grades_exam_student UNIQUE (exam_id, student_id);
ALTER TABLE grades ADD CONSTRAINT fk_grades_exams FOREIGN KEY (exam_id) REFERENCES exams(id);
ALTER TABLE grades ADD CONSTRAINT fk_grades_users FOREIGN KEY (student_id) REFERENCES users(id);

CREATE TABLE warnings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    created_at TIMESTAMP
);
ALTER TABLE warnings ADD CONSTRAINT pk_warnings PRIMARY KEY (id);
ALTER TABLE warnings ADD CONSTRAINT fk_warnings_exams FOREIGN KEY (exam_id) REFERENCES exams(id);

CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL
);
ALTER TABLE registrations ADD CONSTRAINT pk_registrations PRIMARY KEY (id);
ALTER TABLE registrations ADD CONSTRAINT uk_registrations_student_class UNIQUE (student_id, class_id);
ALTER TABLE registrations ADD CONSTRAINT fk_registrations_users FOREIGN KEY (student_id) REFERENCES users(id);
ALTER TABLE registrations ADD CONSTRAINT fk_registrations_classes FOREIGN KEY (class_id) REFERENCES classes(id);

CREATE TABLE final_exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    exam_date DATE NOT NULL,
    max_score DECIMAL(5,2) DEFAULT 100,
    min_score DECIMAL(5,2) DEFAULT 80
);
ALTER TABLE final_exams ADD CONSTRAINT pk_final_exams PRIMARY KEY (id);
ALTER TABLE final_exams ADD CONSTRAINT fk_final_exams_classes FOREIGN KEY (class_id) REFERENCES classes(id);
ALTER TABLE final_exams ADD CONSTRAINT fk_final_exams_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id);
ALTER TABLE final_exams ADD CONSTRAINT fk_final_exams_users FOREIGN KEY (teacher_id) REFERENCES users(id);

CREATE TABLE final_grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    final_exam_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    grade DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (final_exam_id) REFERENCES final_exams(id),
    FOREIGN KEY (student_id) REFERENCES users(id)
);
ALTER TABLE final_grades ADD CONSTRAINT pk_final_grades PRIMARY KEY (id);
ALTER TABLE final_grades ADD CONSTRAINT uk_final_grades_final_exam_student UNIQUE (final_exam_id, student_id);
ALTER TABLE final_grades ADD CONSTRAINT fk_final_grades_final_exams FOREIGN KEY (final_exam_id) REFERENCES final_exams(id);
ALTER TABLE final_grades ADD CONSTRAINT fk_final_grades_users FOREIGN KEY (student_id) REFERENCES users(id);