DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS subjects CASCADE;
DROP TABLE IF EXISTS exams CASCADE;
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS warnings CASCADE;
DROP TABLE IF EXISTS registration CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL
);
ALTER TABLE users ADD CONSTRAINT pk_users PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT uk_users_email UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT ck_users_type CHECK (type IN ('STUDENT', 'TEACHER', 'ADMIN'));

CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL
);
ALTER TABLE classes ADD CONSTRAINT pk_classes PRIMARY KEY (id);

CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(200) NOT NULL
);
ALTER TABLE subjects ADD CONSTRAINT pk_subjects PRIMARY KEY (id);

CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    exam_date DATE NOT NULL
);
ALTER TABLE exams ADD CONSTRAINT pk_exams PRIMARY KEY (id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_classes FOREIGN KEY (class_id) REFERENCES classes(id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_subjects FOREIGN KEY (subject_id) REFERENCES subjects(id);
ALTER TABLE exams ADD CONSTRAINT fk_exams_users FOREIGN KEY (teacher_id) REFERENCES users(id);

CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    grade DECIMAL(5,2) NOT NULL
);
ALTER TABLE grades ADD CONSTRAINT pk_grades PRIMARY KEY (id);
ALTER TABLE grades ADD CONSTRAINT uk_grades_exam_student UNIQUE (exam_id, student_id);
ALTER TABLE grades ADD CONSTRAINT fk_grades_exams FOREIGN KEY (exam_id) REFERENCES exams(id);
ALTER TABLE grades ADD CONSTRAINT fk_grades_users FOREIGN KEY (student_id) REFERENCES users(id);

CREATE TABLE warnings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE warnings ADD CONSTRAINT pk_warnings PRIMARY KEY (id);
ALTER TABLE warnings ADD CONSTRAINT fk_warnings_exams FOREIGN KEY (exam_id) REFERENCES exams(id);

CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL
);
ALTER TABLE registration ADD CONSTRAINT pk_registration PRIMARY KEY (id);
ALTER TABLE registration ADD CONSTRAINT uk_registration_student_class UNIQUE (student_id, class_id);
ALTER TABLE registration ADD CONSTRAINT fk_registration_users FOREIGN KEY (student_id) REFERENCES users(id);
ALTER TABLE registration ADD CONSTRAINT fk_registration_classes FOREIGN KEY (class_id) REFERENCES classes(id);